import { Inter } from &apos;next/font/google&apos;
import &apos;./globals.css&apos;

const inter = Inter({ subsets: [&apos;latin&apos;] })

export const metadata = {
  title: &apos;One Aim IT Solutions&apos;,
  description: &apos;Generated by create next app&apos;,
}

export default function RootLayout({ children }) {
  return (
    <html lang=&quot;en&quot;>
      <body className={`${inter.className}`}>{children}</body>
    </html>
  )
}
